version: "3"
services:
  #サービス名
  web:
    build: .  # ビルドパスを修正
    environment:
      SECRET_KEY_BASE: "ango;J`OJ'#eg4789\/[hk@"
      RAILS_ENV: production
    command: >
      sh -c "
             bundle exec puma -C config/puma.rb"
#bundle exec rails assets:precompile &&
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  db-volume:
